// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ckYvNiMXYy9Rm7703xZwLLLctEwbsKQ',
    appId: '1:878190107913:web:4687765d1dfc1368f7c7d8',
    messagingSenderId: '878190107913',
    projectId: 'cufitness-347c4',
    authDomain: 'cufitness-347c4.firebaseapp.com',
    storageBucket: 'cufitness-347c4.firebasestorage.app',
    measurementId: 'G-XCLNJDGNY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHxQup42Xfm38DeaQaeK0_2IZ20AiNLk',
    appId: '1:878190107913:android:d497205e4947a473f7c7d8',
    messagingSenderId: '878190107913',
    projectId: 'cufitness-347c4',
    storageBucket: 'cufitness-347c4.firebasestorage.app',
  );
}
